[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"

[build]
  command = "npx puppeteer browsers install chrome && npm run build"
  publish = "_site"

